version: '2'
services:
    elastalert:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: elastalert
        working_dir: /home/elastalert
        volumes:
            - ./:/home/elastalert/
